const eng = {
    "wip.main": "Coming soon...",
    "wip.ok": "OK",
    "more-menu.switch-theme": "Switch theme",
    "more-menu.document": "PNX docs",
    "more-menu.switch-to-day": "Switched to day theme",
    "more-menu.switch-to-night": "Switched to night theme",
    "more-menu.ok": "OK",
    "logo-des-mcbe-server": "MCBE server software",
    "logo-des-0": "High-performance, feature-rich, fully open source ",
    "logo-des-1": "Multi-core parallel computing ",
    "logo-des-2": "Vanilla commands and command blocks supported ",
    "logo-des-3": "JS plugin engine within ",
    "logo-des-4": "Java17 & ES13 based",
    "logo-des-5": "0% Microsoft/mojang code ",
    "logo-des-6": "Redstone supported ",
    "logo-des-7": "384-height worlds ",
    "logo-des-8": "Multi-world supported ",
    "logo-des-9": "Epic world generator within ",
    "link.source-code": "Source Code",
    "text.why-choose-pnx": "Why choose PNX?",
    "text.servers-choice": "Many servers' choice",
    "text.servers": "servers",
    "text.running-pnx": "are running PNX",
    "text.on-github": "on Github",
    "text.thanks": "Thanks for ",
    "倾囊相助": "generous sponsorship",
    "慷慨解囊": "sponsorship",
    "精神支持": "support",
    "text.thanks-month-sponsors": "Thanks to sponsors this month",
    "text.thanks-all-sponsors": "Thanks to all sponsors",

    "text.high-performance": "High performance",
    "text.high-performance.description": "Multi-core parallel computing + Graal JIT",
    "text.high-performance.content": "The parallel processing capability of PNX enables it to make full use of multi-core CPU. You don't need to pursue high CPU frequency, and you can enjoy the huge performance improvement brought by multi-core CPU. At the same time, we use the world's leading graaljit compiler to dynamically convert java code into high-quality machine code most suitable for your CPU, so that Java code has high performance comparable to C++.",

    "text.more-feature": "Vanilla features",
    "text.more-feature.description": "All blocks, items, recipes, etc.",
    "text.more-feature.content": "PNX supports more vanilla features, including but not limited to all blocks, items, recipes, redstone, vanilla commands, water-logged blocks, etc. PNX is committed to providing a better survival mode game experience.",

    "text.massive-plugins": "Massive plugins",
    "text.massive-plugins.description": "Thousands of plugins for you to choose",
    "text.massive-plugins.content": "PNX retains good plugin compatibility while adding many vanilla features, and can directly run Java plugins written targeting nukkitx and PowerMockito. In addition, PNX also implements the JSAPI of LiteLoader based on the built-in JS engine, which enables LLSE plugins to run on PNX with only a few changes.",

    "text.vanilla-command": "Vanilla command",
    "text.vanilla-command.description": "Vanilla command & command blocks",
    "text.vanilla-command.content": "PNX allows you to use the vanilla commands and command blocks in your server. The vast majority of the original commands and mcfunction files can work on PNX. You can quickly customize your server using the command block.",

    "text.js-engine": "JS Plugin",
    "text.js-engine.description": "JS plugins based on ES13 & ESM",
    "text.js-engine.content": "You can use JS to quickly write PNX based plugins. The JS plugin engine based on ES13 standard and ESM enables you to build large plugins quickly and stably, while maintaining good cross plugin interaction. JS plugins can directly interact with other JS or Java plugins, and be compiled together with Java bytecode, breaking language boundaries and obtaining ultra-high performance.",

    "text.and-more": "And more...",
    "text.and-more.description": "More advantages are waiting you to explore.",
    "text.and-more.content": "PNX has countless other advantages, waiting to meet you in the process of using it.",

    "text.awesome-pnx": "Awesome PNX",
    "pnx.awesome.more": "Find more...",
    "pnx.awesome.click-to-see-more": "Click to see more about PNX",
}
const chn = {
    "wip.main": "此功能正在开发中",
    "wip.ok": "确认",
    "more-menu.switch-theme": "切换主题",
    "more-menu.document": "PNX文档",
    "more-menu.switch-to-day": "已切换至日间主题",
    "more-menu.switch-to-night": "已切换至夜间主题",
    "more-menu.ok": "确认",
    "logo-des-mcbe-server": "的MCBE服务端",
    "logo-des-0": "高性能、富特性、全开源",
    "logo-des-1": "多核并行计算",
    "logo-des-2": "支持原版命令和命令方块",
    "logo-des-3": "自带JS插件引擎",
    "logo-des-4": "基于Java17和ES13",
    "logo-des-5": "0%来自微软/mojang代码",
    "logo-des-6": "支持原版红石电路",
    "logo-des-7": "拥有384格全新世界",
    "logo-des-8": "支持单端多世界",
    "logo-des-9": "能够生成壁纸级史诗地形",
    "link.source-code": "源代码",
    "text.why-choose-pnx": "为什么选择PNX？",
    "text.servers-choice": "众多服务器的共同选择",
    "text.servers": "台服务器",
    "text.running-pnx": "此刻正在运行PNX",
    "text.on-github": "在Github平台上",
    "text.thanks": "感谢您",
    "text.thanks-month-sponsors": "感谢本月赞助者",
    "text.thanks-all-sponsors": "感谢所有赞助者",

    "text.high-performance": "高性能",
    "text.high-performance.description": "多核并行计算 + Graal即时编译器",
    "text.high-performance.content": "PNX的并行处理能力使得其能够更充分地利用多核CPU，您无需追求CPU高主频，可以享受多核心CPU带来的巨大性能提升。同时，我们引入世界领先的GraalJIT编译器，将java代码动态转换为最适合您的CPU的高质量机器码，让java代码拥有堪比C++的高性能。",

    "text.more-feature": "更多原版特性",
    "text.more-feature.description": "高版本方块、物品、合成等应有尽有",
    "text.more-feature.content": "PNX支持更多原版特性，包括但不限于所有原版方块、物品及其合成，红石电路，原版命令，含水方块等。PNX致力于提供更好的生存游戏体验。",

    "text.massive-plugins": "海量插件",
    "text.massive-plugins.description": "数千插件，任您选用",
    "text.massive-plugins.content": "PNX在添加众多原版特性的同时仍保留了较好的插件兼容性，能够直接运行基于NukkitX和PowerNukkit编写的Java插件。此外，PNX还基于内置的JS引擎实现了LiteLoader的JSAPI，这使得LLSE插件经过少许更改即可运行在PNX上。",

    "text.vanilla-command": "原版命令",
    "text.vanilla-command.description": "支持原版命令和命令方块",
    "text.vanilla-command.content": "PNX允许您在游戏中使用原版命令和命令方块，绝大多数原版命令和mcfunction文件都可以在pnx上使用。您可以使用命令方块快捷地自定义您的服务器。",

    "text.js-engine": "JS插件",
    "text.js-engine.description": "基于ES13标准和ESM的现代化JS插件",
    "text.js-engine.content": "您可以使用JS快速编写基于PNX的插件。基于ES13标准和ESM的JS插件引擎使得您可以快速稳定地构建大型插件，同时保留良好的跨插件交互性，JS插件可以与其他JS或Java插件无缝交互，与Java代码一道被融合编译，打破语言边界，获取超高性能。",

    "text.and-more": "还有更多...",
    "text.and-more.description": "更多优点等待您探索",
    "text.and-more.content": "PNX还有其他数不胜数的优点，等待着在您在使用的过程中与您邂逅。",

    "text.awesome-pnx": "发现PNX",
    "pnx.awesome.more": "发现更多",
    "pnx.awesome.click-to-see-more": "点击查看更多关于PNX的内容",
}